---
title: "Template Analysis"
author: "Erin Cain"
date: "1/31/2022"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Explore UWMP Data: 
- Table 4-3 Wholesale: Total Water Demands  (Converted to Acre-Feet)
- Table 2-1 Retail Only: Public Water Systems (Converted to Acre-Feet)

*Many other tables that may be useful to look at 
```{r, message=FALSE, warning=FALSE}

# May want to look at retail total water demands as well 
UWMP_demand <- readxl::read_excel("../data-raw/uwmp_table_4_3_w_view_conv_to_af.xlsx") %>% 
  filter(WATER_SUPPLIER_NAME == "Healdsburg  City Of") %>%
  glimpse()

UWMP_supply <- readxl::read_excel("../data-raw/uwmp_table_2_2_r_conv_to_af.xlsx") %>% 
  filter(WATER_SUPPLIER_NAME == "Healdsburg  City Of") %>%
  glimpse()



unique(UWMP_supply$WATER_SUPPLIER_NAME)

UWMP_supply_fields <- colnames(UWMP_supply)

UWMP_demand_fields <- colnames(UWMP_demand)

# UWMP_fields <- unique(append(cols_UWMP_demand, cols_UWMP_supply))


write_rds(UWMP_demand_fields, "../data/UWMP_demand_fields.rds")
write_rds(UWMP_supply_fields, "../data/UWMP_supply_fields.rds")
```

## Explore Water Loss Report Data (Converted to Acre-Feet)
```{r message=FALSE, warning=FALSE}
WLR <- readxl::read_excel("../data-raw/water_audit_data_conv_to_af.xlsx") %>% 
  filter(REPORTING_YEAR == 2020, WATER_SUPPLIER_NAME == "Healdsburg  City Of") %>% 
  glimpse()

unique(WLR$WATER_SUPPLIER_NAME)

WLR_fields <- colnames(WLR)

WLR_supply_fields <- WLR_fields[stringr::str_detect(colnames(WLR), "^WS")]
WLR_demand_fields <- WLR_fields[stringr::str_detect(colnames(WLR), "^AC")]
WLR_other_fields <- WLR_fields[!stringr::str_detect(colnames(WLR), "^AC") & !stringr::str_detect(colnames(WLR), "^WS")]
# write_rds(WLR_fields, "../data/WLR_fields.rds")

write_rds(WLR_supply_fields, "../data/WLR_supply_fields.rds")
write_rds(WLR_demand_fields, "../data/WLR_demand_fields.rds")
write_rds(WLR_other_fields, "../data/WLR_other_fields.rds")
```


## Explore Conservation Report Data 
```{r}
conservation_report <- readxl::read_excel("../data-raw/conservation-report-uw-supplier-data120721.xlsx") %>% 
  glimpse

conservation_report_fields <- colnames(conservation_report)

conservation_background_fields <- c("Supplier Name", "Public Water System ID", "Reporting Month", "County", 
                                    "Hydrologic Region", "Climate Zone", "Total Population Served", 
                                    "Reference 2014 Population", "County Under Drought Declaration", 
                                    "Water Shortage Contingency Stage Invoked", "Water Shortage Level Indicator", 
                                    "Water Production Units")

conservation_supply_fields <- c("REPORTED PRELIMINARY Total Potable Water Production", "REPORTED FINAL Total Potable Water Production")

conservation_demand_fields <- c("PRELIMINARY Percent Residential Use","FINAL Percent Residential Use", 
                                "REPORTED PRELIMINARY Commercial Agricultural Water", "REPORTED FINAL Commercial Agricultural Water", 
                                "REPORTED PRELIMINARY Commercial, Industrial, and Institutional Water", 
                                "REPORTED FINAL Commercial, Industrial, and Institutional Water", "REPORTED Recycled Water", 
                                "REPORTED Non-Revenue Water")

conservation_calculated_fields <- c("CALCULATED Total Potable Water Production Gallons (Ag Excluded)", 
                                    "CALCULATED Total Potable Water Production Gallons 2013 (Ag Excluded)", 
                                    "CALCULATED Commercial Agricultural Water Gallons", 
                                    "CALCULATED Commercial Agricultural Water Gallons 2013", "CALCULATED R-GPCD", "Qualification")
# write_rds(conservation_report_fields, "../data/conservation_report_fields.rds")
write_rds(conservation_supply_fields, "../data/conservation_supply_fields.rds")
write_rds(conservation_demand_fields, "../data/conservation_demand_fields.rds")
write_rds(conservation_calculated_fields, "../data/conservation_calculated_fields.rds")
write_rds(conservation_background_fields, "../data/conservation_background_fields.rds")
```

## Explore EAR Report Data 
```{r}
EAR_report <- read.delim("../data-raw/EAR_ResultSet_2020RY.txt") %>% 
  glimpse

filtered_EAR_report <- EAR_report %>% 
  filter(SurveyName == "2020 EAR", SectionID %in% c("06 Supply-Delivery")) %>% 
  mutate(QuestionType = substr(QuestionName, start = 1, stop = 2),
         month = stringr::str_extract(QuestionName, month.abb),
         # length = length(QuestionName),
         category = ifelse(is.na(month), 
                           substr(QuestionName, start = 3, stop = length(QuestionName)), 
                           substr(QuestionName, start = 6, stop = length(QuestionName)))) %>% glimpse()

unique(filtered_EAR_report$month)
# Lots of fields here, not sure how to best select metrics of interest 

EAR_fields <- unique(filtered_EAR_report$QuestionName)
EAR_fields

EAR_supply_fields <- EAR_fields[stringr::str_detect(EAR_fields, "^WP")]
EAR_demand_fields <- EAR_fields[stringr::str_detect(EAR_fields, "^WD")]

write_rds(EAR_supply_fields, "../data/EAR_supply_fields.rds")
write_rds(EAR_demand_fields, "../data/EAR_demand_fields.rds")


metrics_of_interest <- c("WPAnnualTotal", "WDAnnualTotal")
```
